# Generated by Django 2.2.6 on 2019-10-17 02:58

import core_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=core_app.models.recipe_image_file_path),
        ),
    ]
